---
  - name: Install httpd and php (CentOS)
    dnf:
      name:
        - httpd
        - php
      state: present
    when: ansible_distribution == "CentOS"

  - name: Install mariadb package (CentOS)
    yum:
      name: mariadb-server
      state: present
    when: ansible_distribution == "CentOS"

  - name: Start httpd (CentOS)
    service:
      name: httpd
      state: started
    when: ansible_distribution == "CentOS"

  - name: Start MariaDB (CentOS)
    service:
      name: mariadb
      state: started
    when: ansible_distribution == "CentOS"

  - name: Enable httpd (CentOS)
    service:
      name: httpd
      enabled: true
    when: ansible_distribution == "CentOS"

  - name: Enable MariaDB (CentOS)
    service:
      name: mariadb
      enabled: true
    when: ansible_distribution == "CentOS"

  - name: Install httpd and php (Ubuntu)
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: present
    when: ansible_distribution == "Ubuntu"

  - name: Install mariadb package (Ubuntu)
    apt:
      name: mariadb-server
      state: present
    when: ansible_distribution == "Ubuntu"

  - name: Start httpd (Ubuntu)
    service:
      name: apache2
      state: started
    when: ansible_distribution == "Ubuntu"

  - name: Start MariaDB (Ubuntu)
    service:
      name: mariadb
      state: started
    when: ansible_distribution == "Ubuntu"

  - name: Enable httpd (Ubuntu)
    service:
      name: apache2
      enabled: true
    when: ansible_distribution == "Ubuntu"

  - name: Enable MariaDB (Ubuntu)
    service:
      name: mariadb
      enabled: true
    when: ansible_distribution == "Ubuntu"
